# Generated by Django 6.0.5 on 2026-05-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PulseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(choices=[('hero_badges', 'Hero Badges'), ('intro_stats', 'Intro Stats'), ('why_pulse', 'Why Pulse'), ('backed_by', 'Backed By'), ('certifications', 'Certifications'), ('other', 'Other')], help_text='Which section of the website this belongs to', max_length=100)),
                ('label_text', models.CharField(help_text="Display text e.g. 'ISO', 'Made in India', '500+'", max_length=200)),
                ('value_metric', models.CharField(blank=True, help_text="Optional metric e.g. '72 Hrs', '65+ Yrs'", max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to show/hide this item on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pulse Content',
                'verbose_name_plural': 'Pulse Content Items',
                'ordering': ['section_name', 'label_text'],
            },
        ),
    ]
