# Generated by Django 6.0.5 on 2026-05-21 05:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(help_text='Short summary shown in listings', max_length=500)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('author', models.CharField(default='Pulse Team', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('demo', 'Request a Demo'), ('quote', 'Get a Quote'), ('contact', 'Contact Us'), ('support', 'Service Support')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('product_interest', models.CharField(blank=True, max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Form Submission',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description, max 160 chars', max_length=160)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('critical_care', 'Critical Care'), ('renal_care', 'Renal Care'), ('cardiac_care', 'Cardiac Care'), ('aesthetics', 'Aesthetics'), ('rehab_therapy', 'Rehab & Therapy'), ('hospital_setup', 'Hospital Setup')], max_length=50)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('badge_text', models.CharField(blank=True, help_text='e.g. ICU GRADE, OT GRADE', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
    ]
